### ISSUE TITLE
[Feature] Return error on the login page if the status code != 200

### ISSUE THREAD

**Issue by MrKaKisen** [rubentalstra/Pterodactyl-app#21]
If I enter an invalid API KEY and/or an invalid URL, the Server List just shows up as empty. There are no indications for the user that the app is in fact unable to connect to the panel. Might be misleading for new users.

**Comment by rubentalstra** [comment]
That’s a good problem but I have no idee how to verify if the API key or the URL are good.

**Comment by MrKaKisen** [comment]
Maybe let the application perform some kind of action, and if it fails, it means that either the API KEY or the URL is invalid?

**Comment by rubentalstra** [comment]
Oh like a test run? If I get data? I will look if I can do that.

**Comment by ZeProf2Code** [comment]
You just need to perform a http request and see if the http code isn't equal to `200`

**Comment by DarthShmev** [comment]
What ZeProf2Code suggested is exactly what you need to do. Also, why is this labelled bug?

**Comment by rubentalstra** [comment]
its already in the app. but thank you 👍

**Comment by Rhydium** [comment]
@DartShmev, I think it's getting fixed in the new update. Look at the develop branch and then the language files
