### ISSUE TITLE
App name is in lowercase when installed on device

### ISSUE THREAD

**Issue by MrKaKisen** [rubentalstra/Pterodactyl-app#22]
Not sure if this can be classified as an issue, but the name of the app (Pterodactyl App) is in lowercase letters when installed on the device (first letters are uppercase in Google Play).

See attached image.
![pterodactyl_app](https://user-images.githubusercontent.com/15460993/57382532-6b00b480-71ad-11e9-9725-0ea31ea3a110.jpg)

**Comment by rubentalstra** [comment]
I can’t do a much about that right now but I will look into that. Thank you for letting me know.

**Comment by rubentalstra** [comment]
it's fixet thank you
