### ISSUE TITLE
[BUG] Example on the panel url is just ...

### ISSUE THREAD

**Issue by DamonOnYT** [rubentalstra/Pterodactyl-app#23]
**Describe the bug**
On the app login screen, the example is ...

**To Reproduce**
1. Open the app

**Expected behavior**
It is meant to show an example of what a link should look like

**Screenshots**
https://cdn.discordapp.com/attachments/574327246546796544/575993777550917632/Screenshot_20190509-203308.jpg
https://cdn.discordapp.com/attachments/574327246546796544/575994640315056138/Screenshot_20190509-203643.jpg

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A5 2017
 - OS: Android
 - Browser N/A
 - Version: Android 8 / Samsung Experience 9

**Additional context**

**Comment by rubentalstra** [comment]
this issue is fixed thank you for letting me know
