### ISSUE TITLE
[BUG] Too long text / too large font

### ISSUE THREAD

**Issue by J0rdoe** [rubentalstra/Pterodactyl-app#25]
**Describe the bug**
The text is too large / too long to fit properly in the screen

**To Reproduce**
1. Open the app
2. Fill in the API key and the URL

**Expected behavior**
That the font was somewhat smaller so that it was easy to read

**Screenshots**
https://strawpoll.nl/DujNi4CxR.png
https://strawpoll.nl/bA1PURuuy.png
https://strawpoll.nl/nUbAf7QDO.png

**Smartphone (please complete the following information):**
 - Device: Huawei P20 P
 - Android Version: Android Pie (9)

**Comment by DeveloperBoy** [comment]
The screenshot url's aren't working (anymore).

**Comment by J0rdoe** [comment]
> The screenshot urls aren't working (anymore).

Oops, fixed.

**Comment by rubentalstra** [comment]
That’s all an old update that’s all fixed in the new update but where are waiting to update the app.
