### ISSUE TITLE
[BUG] Error when opening a user in the user list

### ISSUE THREAD

**Issue by J0rdoe** [rubentalstra/Pterodactyl-app#39]
**Describe the bug**
Error when opening a user in the user list

**To Reproduce**
1. Open the app
2. Fill in the Admin API key and the URL
3. Go to "Total Users" and click on a user. 

**Expected behavior**
That you can change the user or only see the user(s) without errors. 

**Screenshots**
https://cdn.discordapp.com/attachments/518162001030152203/577495612497461269/Screenshot_20190513-155906.jpg

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - Android Version: Android Pie (9)

**Comment by rubentalstra** [comment]
The user info specific is not ready yet that’s why I’m working on it. Thank you for letting me know.

**Comment by rubentalstra** [comment]
thank you the bug is fixed <3
