### ISSUE TITLE
[BUG] Error while trying to rebuilt, reinstall, suspend and unsuspend a server via the admin part.

### ISSUE THREAD

**Issue by J0rdoe** [rubentalstra/Pterodactyl-app#40]
**Describe the bug**
Error while trying to rebuilt, reinstall, suspend and unsuspend a server via the admin part. 

**To Reproduce**
1. Open the app
2. Fill in the Admin API key and the URL
3. Go to servers and click on a server.
4. Click on one of the buttons

**Expected behavior**
That the button executes the action instead of an error

**Screenshots**
https://cdn.discordapp.com/attachments/518162001030152203/577495612497461271/Screenshot_20190513-160032.jpg

**Smartphone (please complete the following information):**
- Device: Huawei P20 Pro
- Android Version: Android Pie (9)

**Comment by rubentalstra** [comment]
Oh I didn’t know I tested it I will look at it right now. Thank you for letting me know.

**Comment by rubentalstra** [comment]
this bug is fixed thank you. <3
