### ISSUE TITLE
[BUG] Client Login not appearing

### ISSUE THREAD

**Issue by DamonOnYT** [rubentalstra/Pterodactyl-app#48]
**Describe the bug**
There is no "Dont have an Admin account? Tap here" on the homepage

**To Reproduce**
1. Turn on your phone
2. Open the app

**Expected behavior**
The dont have an admin account text/button is meant to appear

**Screenshots**
https://cdn.discordapp.com/attachments/578370310772883464/578557612774129665/Screenshot_20190516-222056.jpg

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A5 2017 Model
 - Android Version: Android 8.0.0
- Samsung Experience version: 9.0

**Additional context**
N/A

**Comment by rubentalstra** [comment]
this issue is fixed thank you
