### ISSUE TITLE
[BUG] App crashes with Firebase error in iOS Simulator

### ISSUE THREAD

**Issue by ntimo** [rubentalstra/Pterodactyl-app#63]
**Describe the bug**
When running the app using `flutter run` it always crashes in the iOS simulator directly after opening it.

```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001120366fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001115daac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112036555 +[NSException raise:format:] + 197
	3   Runner                              0x000000010e7233d2 +[FIRApp configure] + 562
	4   Runner                              0x000000010e81af29 -[FLTFirebaseMessagingPlugin initWithChannel:] + 281
	5   Runner                              0x000000010e81ad89 +[FLTFirebaseMessagingPlugin registerWithRegistrar:] + 185
	6   Runner                              0x000000010e71f9c3 +[GeneratedPluginRegistrant registerWithRegistry:] + 115
	7   Runner      <…>
```

**To Reproduce**
1. Clone the project
2. Open the Simulator `open -a Simulator`
3. Run `pod setup?
4. Run `flutter run`

**Expected behavior**
The app should start and work normally.

**Smartphone (please complete the following information):**
 - Device: iPhone Xs (Simulator)
 - iOS Version: 12.2

**Comment by rubentalstra** [comment]
I know that but thank you. I will solve that problem soon. I will contact you when it will be ready is that good?

**Comment by ntimo** [comment]
Sure sounds good, thank you very much 👍

**Comment by rubentalstra** [comment]
Maybe you can follow the steps if you want to. This is the problem I didn’t do the iOS part if this link: 
https://medium.com/flutterpub/enabling-firebase-cloud-messaging-push-notifications-with-flutter-39b08f2ed723

**Comment by Knight1** [comment]
Problem solved. 

App ist starting fine with some tweaks but many warnings, nothing to worry about at this point. But @ntimo mentioned that you do not have any intention to release it to the AppStore?
