### ISSUE TITLE
[BUG] - Nothing happens

### ISSUE THREAD

**Issue by TheSoulrester** [rubentalstra/Pterodactyl-app#73]
In my ptero webinterface - i have one user with 4 diefferent server on one node. But in the app, nothing appears. all counters are showing zero server, zero nodes and zero users.

the url is a http - ip adress
i created a valid api key

**Screenshots**
![kvJOjY8](https://user-images.githubusercontent.com/7083599/58068602-497ed000-7b92-11e9-9e9f-d06e4e218908.jpg)

**Smartphone (please complete the following information):**
Samsung Galaxy S7 Edge
Android 8.x

**Comment by rubentalstra** [comment]
Can you send me the URL what your filling in?

**Comment by TheSoulrester** [comment]
![20190521_123901](https://user-images.githubusercontent.com/7083599/58089661-a8117180-7bc5-11e9-932d-52345e362433.jpg)

**Comment by rubentalstra** [comment]
Are u using an admin key or an client key?

**Comment by TheSoulrester** [comment]
aehm... while I am logged in and am able to see my servers, I had clicked on api keys and created one.

the user is the server administrator

**Comment by rubentalstra** [comment]
I think your using an client key. We are working on that you Will see an error message when your using the wrong key :)

**Comment by TheSoulrester** [comment]
that was it. I used an client key.

thx :)
